spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: root
      username: root
    url: jdbc:mysql://localhost:3306/study

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8081/test/test
            scope:
              - email
              - profile

server:
  port: 8081
